### ISSUE TITLE
Add optional libadwaita setting to `create-project.py`

### ISSUE THREAD

**Issue by adhadse** [Relm4/relm4-template#14]
It would be nice to have libadwaita installed as a dependency either by default or as an option when creating the project. 
GTK is primarily a GNOME oriented library, and it would be convenient on top of a template app creator.

**Comment by AaronErhardt** [comment]
I agree, that would be a good idea. It should be quite easy to enable or disable libadwaita, so we might just default to libadwaita since this is probably what most users want.

**Comment by adhadse** [comment]
I'll make a PR for this asap.

**Comment by sgued** [comment]
I believe this can now be closed.
